// Autogenerated file; do not edit
package imagemagick

public object Resources {
    public enum class Images(
        public val path: String,
    ) {
        CMYKJPG("src/commonTest/resources/Images/CMYK.jpg"),
        CirclePNG("src/commonTest/resources/Images/Circle.png"),
        ConnectedComponentsPNG("src/commonTest/resources/Images/ConnectedComponents.png"),
        CorruptPNG("src/commonTest/resources/Images/Corrupt.png"),
        EightBimJPG("src/commonTest/resources/Images/EightBim.jpg"),
        EightBimTIF("src/commonTest/resources/Images/EightBim.tif"),
        ExifUndefTypeJPG("src/commonTest/resources/Images/ExifUndefType.jpg"),
        FujiFilmFinePixS1ProGIF("src/commonTest/resources/Images/FujiFilmFinePixS1Pro.gif"),
        FujiFilmFinePixS1ProJPG("src/commonTest/resources/Images/FujiFilmFinePixS1Pro.jpg"),
        FujiFilmFinePixS1ProPNG("src/commonTest/resources/Images/FujiFilmFinePixS1Pro.png"),
        ImageMagickICO("src/commonTest/resources/Images/ImageMagick.ico"),
        ImageMagickJPG("src/commonTest/resources/Images/ImageMagick.jpg"),
        ImageMagickTXT("src/commonTest/resources/Images/ImageMagick.txt"),
        InvitationTIF("src/commonTest/resources/Images/Invitation.tif"),
        LetterJPG("src/commonTest/resources/Images/Letter.jpg"),
        Magick_NET_iconPNG("src/commonTest/resources/Images/Magick.NET.icon.png"),
        NoisePNG("src/commonTest/resources/Images/Noise.png"),
        PictureJPG("src/commonTest/resources/Images/Picture.jpg"),
        RedPNG("src/commonTest/resources/Images/Red.png"),
        RoseSparkleGIF("src/commonTest/resources/Images/RöseSparkle.gif"),
        SnakewarePNG("src/commonTest/resources/Images/Snakeware.png"),
        TestPNG("src/commonTest/resources/Images/Test.png"),
        VicelandPNG("src/commonTest/resources/Images/viceland.png"),
        WandICO("src/commonTest/resources/Images/wand.ico"),
        WhiteJPG("src/commonTest/resources/Images/white.jpg"),
        WireframeTIF("src/commonTest/resources/Images/wireframe.tif"),
        ;

        public enum class Coders(
            public val path: String,
        ) {
            Animated_PNG_example_bouncing_beach_ballPNG(
                "src/commonTest/resources/Images/Coders/Animated_PNG_example_bouncing_beach_ball.png",
            ),
            CNStudiosLogoAI("src/commonTest/resources/Images/Coders/CN Studios Logo.ai"),
            IgnoreTagTIF("src/commonTest/resources/Images/Coders/IgnoreTag.tif"),
            PageTIF("src/commonTest/resources/Images/Coders/Page.tif"),
            PixelTIF("src/commonTest/resources/Images/Coders/Pixel.tif"),
            PlayerPSD("src/commonTest/resources/Images/Coders/Player.psd"),
            RAW_KODAK_DC50KDC("src/commonTest/resources/Images/Coders/RAW_KODAK_DC50.KDC"),
            RowsPerStripTIF("src/commonTest/resources/Images/Coders/RowsPerStrip.tif"),
            SwedenHeartEPS("src/commonTest/resources/Images/Coders/SwedenHeart.eps"),
            TestDDS("src/commonTest/resources/Images/Coders/Test.dds"),
            TestMNG("src/commonTest/resources/Images/Coders/Test.mng"),
            TestMP4("src/commonTest/resources/Images/Coders/Test.mp4"),
            EmptyexifAVIF("src/commonTest/resources/Images/Coders/empty-exif.avif"),
            GrimJP2("src/commonTest/resources/Images/Coders/grim.jp2"),
            LayerstylessamplePSD("src/commonTest/resources/Images/Coders/layer-styles-sample.psd"),
            Pdfexamplepassword_originalPDF("src/commonTest/resources/Images/Coders/pdf-example-password.original.pdf"),
            SamplePDF("src/commonTest/resources/Images/Coders/sample.pdf"),
            WizardPSD("src/commonTest/resources/Images/Coders/wizard.psd"),
        }
    }
}
