// Autogenerated file; can be edited manually if necessary
package imagemagick.colors

import kotlinx.cinterop.ExperimentalForeignApi

@ExperimentalStdlibApi
@ExperimentalForeignApi
public object MagickColors {
    /**
     * Gets a system-defined color that has an RGBA value of #00000000.
     */
    public val None: MagickColor = MagickColor.fromRgba(0u, 0u, 0u, 0u)

    /**
     * Gets a system-defined color that has an RGBA value of #00000000.
     */
    public val Transparent: MagickColor = MagickColor.fromRgba(0u, 0u, 0u, 0u)

    /**
     * Gets a system-defined color that has an RGBA value of #F0F8FFFF.
     */
    public val AliceBlue: MagickColor = MagickColor.fromRgba(240u, 248u, 255u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FAEBD7FF.
     */
    public val AntiqueWhite: MagickColor = MagickColor.fromRgba(250u, 235u, 215u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #00FFFFFF.
     */
    public val Aqua: MagickColor = MagickColor.fromRgba(0u, 255u, 255u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #7FFFD4FF.
     */
    public val Aquamarine: MagickColor = MagickColor.fromRgba(127u, 255u, 212u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #F0FFFFFF.
     */
    public val Azure: MagickColor = MagickColor.fromRgba(240u, 255u, 255u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #F5F5DCFF.
     */
    public val Beige: MagickColor = MagickColor.fromRgba(245u, 245u, 220u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FFE4C4FF.
     */
    public val Bisque: MagickColor = MagickColor.fromRgba(255u, 228u, 196u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #000000FF.
     */
    public val Black: MagickColor = MagickColor.fromRgba(0u, 0u, 0u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FFEBCDFF.
     */
    public val BlanchedAlmond: MagickColor = MagickColor.fromRgba(255u, 235u, 205u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #0000FFFF.
     */
    public val Blue: MagickColor = MagickColor.fromRgba(0u, 0u, 255u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #8A2BE2FF.
     */
    public val BlueViolet: MagickColor = MagickColor.fromRgba(138u, 43u, 226u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #A52A2AFF.
     */
    public val Brown: MagickColor = MagickColor.fromRgba(165u, 42u, 42u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #DEB887FF.
     */
    public val BurlyWood: MagickColor = MagickColor.fromRgba(222u, 184u, 135u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #5F9EA0FF.
     */
    public val CadetBlue: MagickColor = MagickColor.fromRgba(95u, 158u, 160u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #7FFF00FF.
     */
    public val Chartreuse: MagickColor = MagickColor.fromRgba(127u, 255u, 0u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #D2691EFF.
     */
    public val Chocolate: MagickColor = MagickColor.fromRgba(210u, 105u, 30u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FF7F50FF.
     */
    public val Coral: MagickColor = MagickColor.fromRgba(255u, 127u, 80u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #6495EDFF.
     */
    public val CornflowerBlue: MagickColor = MagickColor.fromRgba(100u, 149u, 237u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FFF8DCFF.
     */
    public val Cornsilk: MagickColor = MagickColor.fromRgba(255u, 248u, 220u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #DC143CFF.
     */
    public val Crimson: MagickColor = MagickColor.fromRgba(220u, 20u, 60u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #00FFFFFF.
     */
    public val Cyan: MagickColor = MagickColor.fromRgba(0u, 255u, 255u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #00008BFF.
     */
    public val DarkBlue: MagickColor = MagickColor.fromRgba(0u, 0u, 139u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #008B8BFF.
     */
    public val DarkCyan: MagickColor = MagickColor.fromRgba(0u, 139u, 139u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #B8860BFF.
     */
    public val DarkGoldenrod: MagickColor = MagickColor.fromRgba(184u, 134u, 11u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #A9A9A9FF.
     */
    public val DarkGray: MagickColor = MagickColor.fromRgba(169u, 169u, 169u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #006400FF.
     */
    public val DarkGreen: MagickColor = MagickColor.fromRgba(0u, 100u, 0u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #BDB76BFF.
     */
    public val DarkKhaki: MagickColor = MagickColor.fromRgba(189u, 183u, 107u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #8B008BFF.
     */
    public val DarkMagenta: MagickColor = MagickColor.fromRgba(139u, 0u, 139u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #556B2FFF.
     */
    public val DarkOliveGreen: MagickColor = MagickColor.fromRgba(85u, 107u, 47u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FF8C00FF.
     */
    public val DarkOrange: MagickColor = MagickColor.fromRgba(255u, 140u, 0u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #9932CCFF.
     */
    public val DarkOrchid: MagickColor = MagickColor.fromRgba(153u, 50u, 204u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #8B0000FF.
     */
    public val DarkRed: MagickColor = MagickColor.fromRgba(139u, 0u, 0u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #E9967AFF.
     */
    public val DarkSalmon: MagickColor = MagickColor.fromRgba(233u, 150u, 122u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #8FBC8BFF.
     */
    public val DarkSeaGreen: MagickColor = MagickColor.fromRgba(143u, 188u, 139u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #483D8BFF.
     */
    public val DarkSlateBlue: MagickColor = MagickColor.fromRgba(72u, 61u, 139u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #2F4F4FFF.
     */
    public val DarkSlateGray: MagickColor = MagickColor.fromRgba(47u, 79u, 79u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #00CED1FF.
     */
    public val DarkTurquoise: MagickColor = MagickColor.fromRgba(0u, 206u, 209u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #9400D3FF.
     */
    public val DarkViolet: MagickColor = MagickColor.fromRgba(148u, 0u, 211u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FF1493FF.
     */
    public val DeepPink: MagickColor = MagickColor.fromRgba(255u, 20u, 147u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #00BFFFFF.
     */
    public val DeepSkyBlue: MagickColor = MagickColor.fromRgba(0u, 191u, 255u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #696969FF.
     */
    public val DimGray: MagickColor = MagickColor.fromRgba(105u, 105u, 105u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #1E90FFFF.
     */
    public val DodgerBlue: MagickColor = MagickColor.fromRgba(30u, 144u, 255u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #B22222FF.
     */
    public val Firebrick: MagickColor = MagickColor.fromRgba(178u, 34u, 34u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FFFAF0FF.
     */
    public val FloralWhite: MagickColor = MagickColor.fromRgba(255u, 250u, 240u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #228B22FF.
     */
    public val ForestGreen: MagickColor = MagickColor.fromRgba(34u, 139u, 34u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FF00FFFF.
     */
    public val Fuchsia: MagickColor = MagickColor.fromRgba(255u, 0u, 255u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #DCDCDCFF.
     */
    public val Gainsboro: MagickColor = MagickColor.fromRgba(220u, 220u, 220u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #F8F8FFFF.
     */
    public val GhostWhite: MagickColor = MagickColor.fromRgba(248u, 248u, 255u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FFD700FF.
     */
    public val Gold: MagickColor = MagickColor.fromRgba(255u, 215u, 0u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #DAA520FF.
     */
    public val Goldenrod: MagickColor = MagickColor.fromRgba(218u, 165u, 32u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #808080FF.
     */
    public val Gray: MagickColor = MagickColor.fromRgba(128u, 128u, 128u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #008000FF.
     */
    public val Green: MagickColor = MagickColor.fromRgba(0u, 128u, 0u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #ADFF2FFF.
     */
    public val GreenYellow: MagickColor = MagickColor.fromRgba(173u, 255u, 47u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #F0FFF0FF.
     */
    public val Honeydew: MagickColor = MagickColor.fromRgba(240u, 255u, 240u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FF69B4FF.
     */
    public val HotPink: MagickColor = MagickColor.fromRgba(255u, 105u, 180u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #CD5C5CFF.
     */
    public val IndianRed: MagickColor = MagickColor.fromRgba(205u, 92u, 92u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #4B0082FF.
     */
    public val Indigo: MagickColor = MagickColor.fromRgba(75u, 0u, 130u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FFFFF0FF.
     */
    public val Ivory: MagickColor = MagickColor.fromRgba(255u, 255u, 240u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #F0E68CFF.
     */
    public val Khaki: MagickColor = MagickColor.fromRgba(240u, 230u, 140u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #E6E6FAFF.
     */
    public val Lavender: MagickColor = MagickColor.fromRgba(230u, 230u, 250u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FFF0F5FF.
     */
    public val LavenderBlush: MagickColor = MagickColor.fromRgba(255u, 240u, 245u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #7CFC00FF.
     */
    public val LawnGreen: MagickColor = MagickColor.fromRgba(124u, 252u, 0u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FFFACDFF.
     */
    public val LemonChiffon: MagickColor = MagickColor.fromRgba(255u, 250u, 205u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #ADD8E6FF.
     */
    public val LightBlue: MagickColor = MagickColor.fromRgba(173u, 216u, 230u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #F08080FF.
     */
    public val LightCoral: MagickColor = MagickColor.fromRgba(240u, 128u, 128u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #E0FFFFFF.
     */
    public val LightCyan: MagickColor = MagickColor.fromRgba(224u, 255u, 255u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FAFAD2FF.
     */
    public val LightGoldenrodYellow: MagickColor = MagickColor.fromRgba(250u, 250u, 210u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #D3D3D3FF.
     */
    public val LightGray: MagickColor = MagickColor.fromRgba(211u, 211u, 211u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #90EE90FF.
     */
    public val LightGreen: MagickColor = MagickColor.fromRgba(144u, 238u, 144u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FFB6C1FF.
     */
    public val LightPink: MagickColor = MagickColor.fromRgba(255u, 182u, 193u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FFA07AFF.
     */
    public val LightSalmon: MagickColor = MagickColor.fromRgba(255u, 160u, 122u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #20B2AAFF.
     */
    public val LightSeaGreen: MagickColor = MagickColor.fromRgba(32u, 178u, 170u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #87CEFAFF.
     */
    public val LightSkyBlue: MagickColor = MagickColor.fromRgba(135u, 206u, 250u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #778899FF.
     */
    public val LightSlateGray: MagickColor = MagickColor.fromRgba(119u, 136u, 153u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #B0C4DEFF.
     */
    public val LightSteelBlue: MagickColor = MagickColor.fromRgba(176u, 196u, 222u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FFFFE0FF.
     */
    public val LightYellow: MagickColor = MagickColor.fromRgba(255u, 255u, 224u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #00FF00FF.
     */
    public val Lime: MagickColor = MagickColor.fromRgba(0u, 255u, 0u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #32CD32FF.
     */
    public val LimeGreen: MagickColor = MagickColor.fromRgba(50u, 205u, 50u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FAF0E6FF.
     */
    public val Linen: MagickColor = MagickColor.fromRgba(250u, 240u, 230u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FF00FFFF.
     */
    public val Magenta: MagickColor = MagickColor.fromRgba(255u, 0u, 255u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #800000FF.
     */
    public val Maroon: MagickColor = MagickColor.fromRgba(128u, 0u, 0u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #66CDAAFF.
     */
    public val MediumAquamarine: MagickColor = MagickColor.fromRgba(102u, 205u, 170u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #0000CDFF.
     */
    public val MediumBlue: MagickColor = MagickColor.fromRgba(0u, 0u, 205u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #BA55D3FF.
     */
    public val MediumOrchid: MagickColor = MagickColor.fromRgba(186u, 85u, 211u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #9370DBFF.
     */
    public val MediumPurple: MagickColor = MagickColor.fromRgba(147u, 112u, 219u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #3CB371FF.
     */
    public val MediumSeaGreen: MagickColor = MagickColor.fromRgba(60u, 179u, 113u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #7B68EEFF.
     */
    public val MediumSlateBlue: MagickColor = MagickColor.fromRgba(123u, 104u, 238u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #00FA9AFF.
     */
    public val MediumSpringGreen: MagickColor = MagickColor.fromRgba(0u, 250u, 154u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #48D1CCFF.
     */
    public val MediumTurquoise: MagickColor = MagickColor.fromRgba(72u, 209u, 204u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #C71585FF.
     */
    public val MediumVioletRed: MagickColor = MagickColor.fromRgba(199u, 21u, 133u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #191970FF.
     */
    public val MidnightBlue: MagickColor = MagickColor.fromRgba(25u, 25u, 112u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #F5FFFAFF.
     */
    public val MintCream: MagickColor = MagickColor.fromRgba(245u, 255u, 250u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FFE4E1FF.
     */
    public val MistyRose: MagickColor = MagickColor.fromRgba(255u, 228u, 225u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FFE4B5FF.
     */
    public val Moccasin: MagickColor = MagickColor.fromRgba(255u, 228u, 181u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FFDEADFF.
     */
    public val NavajoWhite: MagickColor = MagickColor.fromRgba(255u, 222u, 173u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #000080FF.
     */
    public val Navy: MagickColor = MagickColor.fromRgba(0u, 0u, 128u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FDF5E6FF.
     */
    public val OldLace: MagickColor = MagickColor.fromRgba(253u, 245u, 230u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #808000FF.
     */
    public val Olive: MagickColor = MagickColor.fromRgba(128u, 128u, 0u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #6B8E23FF.
     */
    public val OliveDrab: MagickColor = MagickColor.fromRgba(107u, 142u, 35u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FFA500FF.
     */
    public val Orange: MagickColor = MagickColor.fromRgba(255u, 165u, 0u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FF4500FF.
     */
    public val OrangeRed: MagickColor = MagickColor.fromRgba(255u, 69u, 0u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #DA70D6FF.
     */
    public val Orchid: MagickColor = MagickColor.fromRgba(218u, 112u, 214u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #EEE8AAFF.
     */
    public val PaleGoldenrod: MagickColor = MagickColor.fromRgba(238u, 232u, 170u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #98FB98FF.
     */
    public val PaleGreen: MagickColor = MagickColor.fromRgba(152u, 251u, 152u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #AFEEEEFF.
     */
    public val PaleTurquoise: MagickColor = MagickColor.fromRgba(175u, 238u, 238u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #DB7093FF.
     */
    public val PaleVioletRed: MagickColor = MagickColor.fromRgba(219u, 112u, 147u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FFEFD5FF.
     */
    public val PapayaWhip: MagickColor = MagickColor.fromRgba(255u, 239u, 213u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FFDAB9FF.
     */
    public val PeachPuff: MagickColor = MagickColor.fromRgba(255u, 218u, 185u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #CD853FFF.
     */
    public val Peru: MagickColor = MagickColor.fromRgba(205u, 133u, 63u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FFC0CBFF.
     */
    public val Pink: MagickColor = MagickColor.fromRgba(255u, 192u, 203u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #DDA0DDFF.
     */
    public val Plum: MagickColor = MagickColor.fromRgba(221u, 160u, 221u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #B0E0E6FF.
     */
    public val PowderBlue: MagickColor = MagickColor.fromRgba(176u, 224u, 230u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #800080FF.
     */
    public val Purple: MagickColor = MagickColor.fromRgba(128u, 0u, 128u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #663399FF.
     */
    public val RebeccaPurple: MagickColor = MagickColor.fromRgba(102u, 51u, 153u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FF0000FF.
     */
    public val Red: MagickColor = MagickColor.fromRgba(255u, 0u, 0u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #BC8F8FFF.
     */
    public val RosyBrown: MagickColor = MagickColor.fromRgba(188u, 143u, 143u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #4169E1FF.
     */
    public val RoyalBlue: MagickColor = MagickColor.fromRgba(65u, 105u, 225u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #8B4513FF.
     */
    public val SaddleBrown: MagickColor = MagickColor.fromRgba(139u, 69u, 19u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FA8072FF.
     */
    public val Salmon: MagickColor = MagickColor.fromRgba(250u, 128u, 114u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #F4A460FF.
     */
    public val SandyBrown: MagickColor = MagickColor.fromRgba(244u, 164u, 96u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #2E8B57FF.
     */
    public val SeaGreen: MagickColor = MagickColor.fromRgba(46u, 139u, 87u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FFF5EEFF.
     */
    public val SeaShell: MagickColor = MagickColor.fromRgba(255u, 245u, 238u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #A0522DFF.
     */
    public val Sienna: MagickColor = MagickColor.fromRgba(160u, 82u, 45u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #C0C0C0FF.
     */
    public val Silver: MagickColor = MagickColor.fromRgba(192u, 192u, 192u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #87CEEBFF.
     */
    public val SkyBlue: MagickColor = MagickColor.fromRgba(135u, 206u, 235u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #6A5ACDFF.
     */
    public val SlateBlue: MagickColor = MagickColor.fromRgba(106u, 90u, 205u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #708090FF.
     */
    public val SlateGray: MagickColor = MagickColor.fromRgba(112u, 128u, 144u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FFFAFAFF.
     */
    public val Snow: MagickColor = MagickColor.fromRgba(255u, 250u, 250u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #00FF7FFF.
     */
    public val SpringGreen: MagickColor = MagickColor.fromRgba(0u, 255u, 127u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #4682B4FF.
     */
    public val SteelBlue: MagickColor = MagickColor.fromRgba(70u, 130u, 180u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #D2B48CFF.
     */
    public val Tan: MagickColor = MagickColor.fromRgba(210u, 180u, 140u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #008080FF.
     */
    public val Teal: MagickColor = MagickColor.fromRgba(0u, 128u, 128u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #D8BFD8FF.
     */
    public val Thistle: MagickColor = MagickColor.fromRgba(216u, 191u, 216u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FF6347FF.
     */
    public val Tomato: MagickColor = MagickColor.fromRgba(255u, 99u, 71u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #40E0D0FF.
     */
    public val Turquoise: MagickColor = MagickColor.fromRgba(64u, 224u, 208u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #EE82EEFF.
     */
    public val Violet: MagickColor = MagickColor.fromRgba(238u, 130u, 238u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #F5DEB3FF.
     */
    public val Wheat: MagickColor = MagickColor.fromRgba(245u, 222u, 179u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FFFFFFFF.
     */
    public val White: MagickColor = MagickColor.fromRgba(255u, 255u, 255u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #F5F5F5FF.
     */
    public val WhiteSmoke: MagickColor = MagickColor.fromRgba(245u, 245u, 245u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #FFFF00FF.
     */
    public val Yellow: MagickColor = MagickColor.fromRgba(255u, 255u, 0u, 255u)

    /**
     * Gets a system-defined color that has an RGBA value of #9ACD32FF.
     */
    public val YellowGreen: MagickColor = MagickColor.fromRgba(154u, 205u, 50u, 255u)
}
